const summary = ["7+ years of experience with all phases of Software Development Life Cycle (SDLC), including Analysis, Design, Development and Testing of applications using n-tier & n-layer Architectures for windows and web applications. ",
    "Experience in Waterfall and Agile Software development methodologies.",
    "Participated in Agile Scrum meetings such as Daily Scrum meetings, Release Planning, Sprint Planning, Backlog Grooming, Retrospective meetings and sprint demo",
    "Developed applications using javascript frameworks such as React,Angular,vue and immutable Js",
    "Redux,Flux and Mobx used to implement state management for React and Angular applications",
    "Rx/js observable pattern used for angular applications",
    "webpack, rollup, grunt and gulp used for bundling the applications",
    "deployed applications to iis, apache and used kestral server for .net core applications",
    "swagger used for documenting the api meta data",
    "Developed Applications using Microsoft.Net Framework, Asp.Net, C#, ADO.NET, LINQ, PLINQ, Entity Framework ,Silverlight, ASP.NET WebApi, WCF, Web Services,DB2, Microsoft Sql server, SSIS, SSAS, Ajax, SSRS  and MongoDB.",
    "Developed applications using third party tools like Telerik, Kendo UI, Aspose Controls, Dapper ORM and Tableau.",
    "Experienced in using Language-Integrated Query (LINQ) query and retrieve data from different data sources (LINQ to Objects, LINQ to XML, LINQ to SQL and PLINQ).",
    "	Experienced in Asynchronous programming for .NET and JavaScript applications.",
    "	Experience in developing rich JavaScript web applications using HTML5, Bootstrap, CSS, Font Awesome, Ajax, D3, JQuery and JavaScript by using AngularJS, React Frameworks.",
    "	Experience in developing RESTFUL API’s using ASP.NET API, Swagger Express API in different data formats such as XML, JSON.",
    "	Experience in developing Data Visualizations using D3 and Tableau.",
    "	Experience in using Object Relational mappers (ORM) like Entity Framework (EF), Dapper ORM and LINQ to SQL.",
    "	Experience in developing predictive modelling algorithms using C#, R.",
    "	Created single page Applications (SPA) using AngularJS, ReactJS, HTML5 and Bootstrap.",
    "	Experience in creating and maintaining HTTP services like Web Service, Windows Commination Services (WCF) and ASP.NET web API. ",
    "	Develop Stored procedures, User defined functions (UDF’s),Indexers, triggers and CTE’s in SQL Server and DB2 environments using T-SQL, PL-SQL and DB2- SQL ",
    "	Experience in developing Custom Reports and different types of Tabular, Matrix, Ad-hoc and distributed reports.",
    "	Expertise in creating and maintaining RDL & RDLC Reports using SQL Server Reporting Services (SSRS).",
    "	Experience in creating drill down, drill through, master and linked reports using SSRS (SQL Server Reporting Services) and Crystal Reports with multi-valued parameters",
    "	Experience in designing Analytical dashboards & Charts using Tableau, Dundas and Performance point.",
    "	Experience in Browsing Cubes and Querying cubes using MDX and DMX.",
    "	Expert in Extraction, Transforming and Loading (ETL) data flows using SSIS; creating mappings/workflows to extract data from SQL Server and Flat File sources and load into various Business Entities.",
    "	Experience in using source control servers like Team Foundation Server(TFS) ,Apache Subversion, Visual Source Safe(VSS), GitLab and GitHub",
    "	Created loosely coupled  and Test Driven(TDD) applications and applied best design patterns such as MVP , MVC and used Ninject and Microsoft unity to resolve dependency ",
    "	Knowledge in creating unit tests using Visual Studio Test System (VSTS) and NUnit. ",
    "	Creating tools and processes to enhance and improve process workflow",
    "	Participated in technical architecture design sessions",
    "	Enthusiastic about learning new concepts in emerging technologies.",
    "	A good team player with excellent interpersonal, communication skills and self-motivated."
]

export default summary